USE [master]
GO

/****** Object:  Database [Database_Poprigog]    Script Date: 24.02.2022 10:58:39 ******/
CREATE DATABASE [Database_Poprigog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Database_Poprigog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Database_Poprigog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Database_Poprigog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Database_Poprigog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Database_Poprigog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Database_Poprigog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Database_Poprigog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Database_Poprigog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Database_Poprigog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Database_Poprigog] SET ARITHABORT OFF 
GO

ALTER DATABASE [Database_Poprigog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Database_Poprigog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Database_Poprigog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Database_Poprigog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Database_Poprigog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Database_Poprigog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Database_Poprigog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Database_Poprigog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Database_Poprigog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Database_Poprigog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Database_Poprigog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Database_Poprigog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Database_Poprigog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Database_Poprigog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Database_Poprigog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Database_Poprigog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Database_Poprigog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Database_Poprigog] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Database_Poprigog] SET  MULTI_USER 
GO

ALTER DATABASE [Database_Poprigog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Database_Poprigog] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Database_Poprigog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Database_Poprigog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Database_Poprigog] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Database_Poprigog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Database_Poprigog] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Database_Poprigog] SET  READ_WRITE 
GO

